[[ROCmDeviceLibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbdb5fc1816ab8918cba29f8cfe9a9055b370d93"
libc = "glibc"
os = "linux"

    [[ROCmDeviceLibs.download]]
    sha256 = "f5af8115918e3971ed38d25e8f617abbe8dbe0f3a31b89d26c1e711f88867ea3"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v5.2.3+0/ROCmDeviceLibs.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmDeviceLibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c44a54d006aaa739180fb116066a3fb08254e26"
libc = "musl"
os = "linux"

    [[ROCmDeviceLibs.download]]
    sha256 = "d7f7b418c1a6048b8392c8ad55dc5158eed966591e41f607f6ec4b8a9679f17a"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v5.2.3+0/ROCmDeviceLibs.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"
