[[ROCmDeviceLibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fda88540064a52d76248d1b0a23c35b9aad2ca7f"
libc = "glibc"
os = "linux"

    [[ROCmDeviceLibs.download]]
    sha256 = "e6ae2cae5cdc9715b0e44ca6e38c7e8afcb7122a7662c8bc1d23d17ace48bba8"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v5.4.4+0/ROCmDeviceLibs.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmDeviceLibs]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fda88540064a52d76248d1b0a23c35b9aad2ca7f"
libc = "musl"
os = "linux"

    [[ROCmDeviceLibs.download]]
    sha256 = "e6ae2cae5cdc9715b0e44ca6e38c7e8afcb7122a7662c8bc1d23d17ace48bba8"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v5.4.4+0/ROCmDeviceLibs.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
