[ROCmDeviceLibs]
git-tree-sha1 = "681dee9b7d460a3b54ce5aba334dc5a8071411e6"

    [[ROCmDeviceLibs.download]]
    sha256 = "75d81c9124d352835c53a5cf8a74659d493fd8e66ad5270109810792559cb703"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v7.0.2+0/ROCmDeviceLibs.v7.0.2.any.tar.gz"
