[ROCmDeviceLibs]
git-tree-sha1 = "b46ab46ef568406312e5f500efb677511199c2f9"

    [[ROCmDeviceLibs.download]]
    sha256 = "96f9b6f0765ea2346fb16ef0f898158eccdfee7cec57a6d46323c914479b977a"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v6.2.1+0/ROCmDeviceLibs.v6.2.1.any.tar.gz"
