[[ROCmDeviceLibs]]
arch = "x86_64"
git-tree-sha1 = "65242d8c88c23806807d43058cdac7ece85e9d4b"
libc = "glibc"
os = "linux"

    [[ROCmDeviceLibs.download]]
    sha256 = "6d60aa6e4cbc28630929a94e28e828dcead6e02e5ee60ead4fb11b921efdb384"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v4.0.0+0/ROCmDeviceLibs.v4.0.0.x86_64-linux-gnu.tar.gz"
[[ROCmDeviceLibs]]
arch = "x86_64"
git-tree-sha1 = "6b428980c319304963ef39c90f724c474fbb11fe"
libc = "musl"
os = "linux"

    [[ROCmDeviceLibs.download]]
    sha256 = "05cdfb2c6e7b16f6c47fab3d482306e7bc31ddf95bf03a9a1ad3bfa929fea21c"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v4.0.0+0/ROCmDeviceLibs.v4.0.0.x86_64-linux-musl.tar.gz"
