[ROCmDeviceLibs]
git-tree-sha1 = "5ad5ecb46e3c334821f54c1feecc6c152b7b6a45"

    [[ROCmDeviceLibs.download]]
    sha256 = "0e0962504aef9ac2aff51623f856caa1ad049f57ecdb455040f53c91b379e2a7"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v5.6.1+1/ROCmDeviceLibs.v5.6.1.any.tar.gz"
