[ROCmDeviceLibs]
git-tree-sha1 = "0a0cad46b7dacc66387ed19e8c0f45b097f46691"

    [[ROCmDeviceLibs.download]]
    sha256 = "fb99c6dc75fa88ccc3535fcb29a1bfedeecc0dbd0defbc770b322a896e1fa99d"
    url = "https://github.com/JuliaBinaryWrappers/ROCmDeviceLibs_jll.jl/releases/download/ROCmDeviceLibs-v6.2.1+2/ROCmDeviceLibs.v6.2.1.any.tar.gz"
