# Autogenerated wrapper script for ROCmDeviceLibs_jll for any
export bitcode_path

JLLWrappers.@generate_wrapper_header("ROCmDeviceLibs")
JLLWrappers.@declare_file_product(bitcode_path)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        bitcode_path,
        "amdgcn/bitcode",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
